[project]
name = "code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "elasticsearch==8.8.0",
    "openai==1.52.2",
    "python-dotenv>=1.2.1",
    "sentence-transformers==2.7.0",
    "torch==2.6.0",
]
